#!/usr/bin/env bash

set -euo pipefail

mode=${1:-dry-run}
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Strictly reuse the successful DeepSeek-V3-6MoE-Half EP64 experiment
# configuration.  Only the three missing ablation cases are selected:
# hierarchical dedup, fixed R2 with hidden replica-gradient sync, and the
# communication-only static layout.
export PAPER32_WORLD_SIZE=${PAPER32_WORLD_SIZE:-64}
export PAPER32_ARTIFACT_PREFIX=${PAPER32_ARTIFACT_PREFIX:-paper64}
export PAPER32_CLUSTER_SLUG=${PAPER32_CLUSTER_SLUG:-huawei12}
export PAPER32_ABLATION_MODEL=${PAPER32_ABLATION_MODEL:-deepseek_v3_6moe_half}
export PAPER32_ABLATION_DATASET=${PAPER32_ABLATION_DATASET:-tulu3}
export PAPER32_CONTAINER_NAME=${PAPER32_CONTAINER_NAME:-tzq_hiermoe_paper32_warmcache_20260729}

export PAPER32_PROFILE_TAG=${PAPER32_PROFILE_TAG:-mb2_ga2_seq15k_lr0_r2route_v1}
export PAPER32_LAYOUT_TAG=${PAPER32_LAYOUT_TAG:-seq15k_lr0_v1}
export PAPER32_COMPUTE_CALIBRATION_ARTIFACT=${PAPER32_COMPUTE_CALIBRATION_ARTIFACT:-results/paper64_deepseekv3_6moe_half_compute_calibration_ep64_mb2_ga2_seq15k_lr0_v2_region.json}

export PAPER32_MICRO_BATCH_SIZE_OVERRIDE=${PAPER32_MICRO_BATCH_SIZE_OVERRIDE:-2}
export PAPER32_GLOBAL_BATCH_SIZE_OVERRIDE=${PAPER32_GLOBAL_BATCH_SIZE_OVERRIDE:-256}
export PAPER32_MAX_SEQ_LEN=${PAPER32_MAX_SEQ_LEN:-15360}
export PAPER32_LR=${PAPER32_LR:-0}
export PAPER32_MAX_STEPS_OVERRIDE=${PAPER32_MAX_STEPS_OVERRIDE:-6}
export PAPER32_STATS_START_STEP_OVERRIDE=${PAPER32_STATS_START_STEP_OVERRIDE:-4}
export PAPER32_STATS_END_STEP_OVERRIDE=${PAPER32_STATS_END_STEP_OVERRIDE:-6}
export PAPER32_LIGHTWEIGHT_TIMING=${PAPER32_LIGHTWEIGHT_TIMING:-1}

export PAPER32_DEFAULT_REDUNDANT_SLOTS=${PAPER32_DEFAULT_REDUNDANT_SLOTS:-4}
export PAPER32_ABLATION_LAYOUT_CASES=${PAPER32_ABLATION_LAYOUT_CASES:-comm_initial_lut}
export PAPER32_ABLATION_CASES=${PAPER32_ABLATION_CASES:-"ablation_dedup ablation_static_r2 ablation_comm"}
export PAPER32_ABLATION_RUN_TAG=${PAPER32_ABLATION_RUN_TAG:-mb2_ga2_seq15k_lr0_hccl16_expand_chunk32k_ablation_v1}

export PAPER32_ABLATION_MASTER_PORT_BASE=${PAPER32_ABLATION_MASTER_PORT_BASE:-31220}
export PAPER32_ABLATION_HCCL_PORT_BASE=${PAPER32_ABLATION_HCCL_PORT_BASE:-65000}
export PAPER32_REUSE_PROFILE=${PAPER32_REUSE_PROFILE:-1}
export PAPER32_PREPARE_EPLB=0
export PYTORCH_NPU_ALLOC_CONF_OVERRIDE=${PYTORCH_NPU_ALLOC_CONF_OVERRIDE:-expandable_segments:True}
export VEOMNI_HIERMOE_INDEX_ADD_FP32_CHUNK_ROWS=${VEOMNI_HIERMOE_INDEX_ADD_FP32_CHUNK_ROWS:-32768}

if [[ "${mode}" == "full" ]]; then
  export PAPER32_CONFIRM_ABLATION=1
fi

exec bash "${script_dir}/run_hiermoe_ablation_matrix.sh" "${mode}"
