#!/usr/bin/env bash
# Qwen3-VL-30B-A3B full 48-layer four-node Ascend NPU light profile.
#
# This script is the NPU counterpart of the GPU 2-node EP16 light-profile
# launch. It keeps MoE router monitoring enabled for every step, while sampling
# full module timing sparsely to avoid writing heavy per-rank JSONL for all 100
# steps.
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/../.." && pwd)
cd "${REPO_ROOT}"

HIERMOE_PLANNER_CUSTOM_OPP_PATH=${HIERMOE_PLANNER_CUSTOM_OPP_PATH:-"${REPO_ROOT}/veomni/ops/platform/npu/hiermoe_planner_ops/build/opp_install/packages/vendors/customize"}
if [[ -d "${HIERMOE_PLANNER_CUSTOM_OPP_PATH}" ]]; then
    case ":${ASCEND_CUSTOM_OPP_PATH:-}:" in
        *":${HIERMOE_PLANNER_CUSTOM_OPP_PATH}:"*) ;;
        *) export ASCEND_CUSTOM_OPP_PATH="${HIERMOE_PLANNER_CUSTOM_OPP_PATH}${ASCEND_CUSTOM_OPP_PATH:+:${ASCEND_CUSTOM_OPP_PATH}}" ;;
    esac
fi

RUN_NAME=${RUN_NAME:-qwen3vl_full48_sharegpt4v_ep32_lightprof_100step_$(date +%Y%m%d_%H%M%S)}
RUN_ROOT=${RUN_ROOT:-"${REPO_ROOT}/pretrain_runs/${RUN_NAME}"}
MODEL_PATH=${MODEL_PATH:-/workspace/model/Qwen3-VL-30B-A3B-Instruct}
DATA_PATH=${DATA_PATH:-/workspace/dataset/ShareGPT4V/sharegpt4v_instruct_gpt4-vision_cap100k_coco_abs_share_full_shards}

NNODES=${NNODES:-4}
NODE_RANK=${NODE_RANK:?NODE_RANK must be set to 0, 1, 2, or 3}
NPROC_PER_NODE=${NPROC_PER_NODE:-8}
MASTER_ADDR=${MASTER_ADDR:-192.168.0.63}
MASTER_PORT=${MASTER_PORT:-29500}
TOTAL_PROCS=$((NNODES * NPROC_PER_NODE))

MAX_STEPS=${MAX_STEPS:-100}
MICRO_BATCH_SIZE=${MICRO_BATCH_SIZE:-1}
GLOBAL_BATCH_SIZE=${GLOBAL_BATCH_SIZE:-32}
MAX_SEQ_LEN=${MAX_SEQ_LEN:-4096}
DATA_NUM_WORKERS=${DATA_NUM_WORKERS:-4}
DATA_PREFETCH_FACTOR=${DATA_PREFETCH_FACTOR:-2}
DP_REPLICATE_SIZE=${DP_REPLICATE_SIZE:-1}
DP_SHARD_SIZE=${DP_SHARD_SIZE:-${TOTAL_PROCS}}
EP_SIZE=${EP_SIZE:-32}
NUM_MOE_LAYERS=${NUM_MOE_LAYERS:-48}
MOE_IMPL=${MOE_IMPL:-fused_npu}
ATTN_IMPL=${ATTN_IMPL:-flash_attention_2}
MOE_MONITOR_INTERVAL=${MOE_MONITOR_INTERVAL:-1}

PROFILE_KIND=${PROFILE_KIND:-pretrain}
VEOMNI_PROFILE_ROOT=${VEOMNI_PROFILE_ROOT:-"${REPO_ROOT}/profile"}
VERL_MOE_PROFILE_DIR=${VERL_MOE_PROFILE_DIR:-"${VEOMNI_PROFILE_ROOT}/runs/${PROFILE_KIND}/${RUN_NAME}"}
VERL_MOE_MONITOR_DIR=${VERL_MOE_MONITOR_DIR:-"${VERL_MOE_PROFILE_DIR}/moe_monitor"}
VERL_MOE_TIMING_DIR=${VERL_MOE_TIMING_DIR:-"${VERL_MOE_PROFILE_DIR}/moe_timing"}
VERL_MOE_TIMING_NUM_LAYERS=${VERL_MOE_TIMING_NUM_LAYERS:-${NUM_MOE_LAYERS}}
VEOMNI_MOE_TIMING_SYNC_EVENTS=${VEOMNI_MOE_TIMING_SYNC_EVENTS:-0}
HIERMOE_DEDUP_ONLY=${HIERMOE_DEDUP_ONLY:-0}

# Light full-timing defaults: warm up steps 1-2, then sample one step every 10.
# MoE monitor remains every step via --train.moe_load_balance_monitor_interval.
VEOMNI_FULL_PROFILE_ENABLE=${VEOMNI_FULL_PROFILE_ENABLE:-1}
VEOMNI_FULL_PROFILE_DIR=${VEOMNI_FULL_PROFILE_DIR:-"${VERL_MOE_PROFILE_DIR}/full_timing"}
VEOMNI_FULL_PROFILE_START_STEP=${VEOMNI_FULL_PROFILE_START_STEP:-3}
VEOMNI_FULL_PROFILE_EVERY_N=${VEOMNI_FULL_PROFILE_EVERY_N:-10}
VEOMNI_FULL_PROFILE_RANKS=${VEOMNI_FULL_PROFILE_RANKS:-all}
VEOMNI_FULL_PROFILE_WITH_BACKWARD=${VEOMNI_FULL_PROFILE_WITH_BACKWARD:-1}
VEOMNI_FULL_PROFILE_RUN_KIND=${VEOMNI_FULL_PROFILE_RUN_KIND:-pretrain}

# Keep torch_npu.profiler disabled for this light profile.
VEOMNI_TORCH_PROFILE_ENABLE=${VEOMNI_TORCH_PROFILE_ENABLE:-0}
VEOMNI_TORCH_PROFILE_DIR=${VEOMNI_TORCH_PROFILE_DIR:-"${VERL_MOE_PROFILE_DIR}/torch_profiler"}
VEOMNI_TORCH_PROFILE_START_STEP=${VEOMNI_TORCH_PROFILE_START_STEP:-3}
VEOMNI_TORCH_PROFILE_END_STEP=${VEOMNI_TORCH_PROFILE_END_STEP:-4}
VEOMNI_TORCH_PROFILE_RANK0_ONLY=${VEOMNI_TORCH_PROFILE_RANK0_ONLY:-true}
VEOMNI_TORCH_PROFILE_EXPORT_RANKS=${VEOMNI_TORCH_PROFILE_EXPORT_RANKS:-0}
VEOMNI_TORCH_PROFILE_RECORD_SHAPES=${VEOMNI_TORCH_PROFILE_RECORD_SHAPES:-false}
VEOMNI_TORCH_PROFILE_PROFILE_MEMORY=${VEOMNI_TORCH_PROFILE_PROFILE_MEMORY:-false}
VEOMNI_TORCH_PROFILE_WITH_STACK=${VEOMNI_TORCH_PROFILE_WITH_STACK:-false}
VEOMNI_TORCH_PROFILE_WITH_MODULES=${VEOMNI_TORCH_PROFILE_WITH_MODULES:-false}
VEOMNI_TORCH_PROFILE_ACTIVITIES=${VEOMNI_TORCH_PROFILE_ACTIVITIES:-cpu,npu}
VEOMNI_MOE_VALIDATOR_ENABLE=${VEOMNI_MOE_VALIDATOR_ENABLE:-0}
VEOMNI_MOE_VALIDATOR_DIR=${VEOMNI_MOE_VALIDATOR_DIR:-"${VERL_MOE_PROFILE_DIR}/moe_validator"}

HIERMOE_ARGS=()
HIERMOE_ENABLE=${HIERMOE_ENABLE:-}
HIERMOE_TOKEN_DEDUP=${HIERMOE_TOKEN_DEDUP:-true}
HIERMOE_COMMUNICATION_MODE=${HIERMOE_COMMUNICATION_MODE:-hierarchical}
HIERMOE_EXPERT_SWAP=${HIERMOE_EXPERT_SWAP:-true}
HIERMOE_EXPERT_SWAP_INTERVAL=${HIERMOE_EXPERT_SWAP_INTERVAL:-1}
HIERMOE_EXPERT_SWAP_MAX_PAIRS_PER_LAYER=${HIERMOE_EXPERT_SWAP_MAX_PAIRS_PER_LAYER:-1}
HIERMOE_EXPERT_SWAP_SELECTOR=${HIERMOE_EXPERT_SWAP_SELECTOR:-current_joint}
HIERMOE_REDUNDANT_SLOT_INCREMENT_PER_DEVICE=${HIERMOE_REDUNDANT_SLOT_INCREMENT_PER_DEVICE:-0}
HIERMOE_GREEDY_MAX_COPIES_PER_EXPERT=${HIERMOE_GREEDY_MAX_COPIES_PER_EXPERT:-4}
HIERMOE_MAX_SLOT_OP_SEARCH_ROUNDS=${HIERMOE_MAX_SLOT_OP_SEARCH_ROUNDS:-}
HIERMOE_EXPERT_SWAP_MODE=${HIERMOE_EXPERT_SWAP_MODE:-step}
HIERMOE_HIERARCHY_GROUP_SIZES=${HIERMOE_HIERARCHY_GROUP_SIZES:-}
HIERMOE_FIT_PERF_MODEL_ON_STARTUP=${HIERMOE_FIT_PERF_MODEL_ON_STARTUP:-0}
HIERMOE_PERF_MODEL_DIR=${HIERMOE_PERF_MODEL_DIR:-"${VERL_MOE_PROFILE_DIR}/hiermoe_perf_model"}
HIERMOE_PERF_MODEL_PATH=${HIERMOE_PERF_MODEL_PATH:-}
HIERMOE_PERF_MODEL_MASTER_PORT=${HIERMOE_PERF_MODEL_MASTER_PORT:-$((MASTER_PORT + 37))}
HIERMOE_PERF_MODEL_MESSAGE_BYTES_CSV=${HIERMOE_PERF_MODEL_MESSAGE_BYTES_CSV:-67108864,134217728,268435456,536870912}
HIERMOE_PERF_MODEL_WARMUP=${HIERMOE_PERF_MODEL_WARMUP:-2}
HIERMOE_PERF_MODEL_ITERS=${HIERMOE_PERF_MODEL_ITERS:-5}
HIERMOE_PERF_MODEL_MEASURE_LAST_N=${HIERMOE_PERF_MODEL_MEASURE_LAST_N:-3}
HIERMOE_PERF_MODEL_HIERARCHY_GROUP_SIZES=${HIERMOE_PERF_MODEL_HIERARCHY_GROUP_SIZES:-${HIERMOE_HIERARCHY_GROUP_SIZES}}
if [[ "${HIERMOE_FIT_PERF_MODEL_ON_STARTUP}" == "1" || "${HIERMOE_FIT_PERF_MODEL_ON_STARTUP}" == "true" ]]; then
    if [[ -z "${HIERMOE_PERF_MODEL_PATH}" ]]; then
        HIERMOE_PERF_MODEL_PATH="${HIERMOE_PERF_MODEL_DIR}/hiermoe_perf_model.json"
    fi
fi
HIERMOE_SHOULD_PASS_PERF_MODEL=0
if [[ "${HIERMOE_DEDUP_ONLY}" == "1" || "${HIERMOE_DEDUP_ONLY}" == "true" ]]; then
    HIERMOE_SHOULD_PASS_PERF_MODEL=1
    HIERMOE_ARGS+=(
        --train.hiermoe.enable true
        --train.hiermoe.token_dedup true
        --train.hiermoe.expert_swap false
        --train.hiermoe.use_from_step 0
    )
elif [[ -n "${HIERMOE_ENABLE}" ]]; then
    if [[ "${HIERMOE_ENABLE}" == "1" || "${HIERMOE_ENABLE}" == "true" ]]; then
        HIERMOE_SHOULD_PASS_PERF_MODEL=1
    fi
    HIERMOE_ARGS+=(
        --train.hiermoe.enable "${HIERMOE_ENABLE}"
        --train.hiermoe.token_dedup "${HIERMOE_TOKEN_DEDUP}"
        --train.hiermoe.expert_swap "${HIERMOE_EXPERT_SWAP}"
        --train.hiermoe.expert_swap_interval "${HIERMOE_EXPERT_SWAP_INTERVAL}"
        --train.hiermoe.expert_swap_max_pairs_per_layer "${HIERMOE_EXPERT_SWAP_MAX_PAIRS_PER_LAYER}"
        --train.hiermoe.expert_swap_selector "${HIERMOE_EXPERT_SWAP_SELECTOR}"
        --train.hiermoe.redundant_slot_increment_per_device "${HIERMOE_REDUNDANT_SLOT_INCREMENT_PER_DEVICE}"
        --train.hiermoe.greedy_max_copies_per_expert "${HIERMOE_GREEDY_MAX_COPIES_PER_EXPERT}"
        --train.hiermoe.expert_swap_mode "${HIERMOE_EXPERT_SWAP_MODE}"
        --train.hiermoe.use_from_step 0
    )
fi
if [[ -n "${HIERMOE_MAX_SLOT_OP_SEARCH_ROUNDS}" && "${HIERMOE_SHOULD_PASS_PERF_MODEL}" == "1" ]]; then
    HIERMOE_ARGS+=(--train.hiermoe.max_slot_op_search_rounds "${HIERMOE_MAX_SLOT_OP_SEARCH_ROUNDS}")
fi
if [[ "${HIERMOE_SHOULD_PASS_PERF_MODEL}" == "1" ]]; then
    HIERMOE_ARGS+=(--train.hiermoe.communication_mode "${HIERMOE_COMMUNICATION_MODE}")
fi
if [[ -n "${HIERMOE_PERF_MODEL_PATH}" && "${HIERMOE_SHOULD_PASS_PERF_MODEL}" == "1" ]]; then
    HIERMOE_ARGS+=(--train.hiermoe.perf_model_path "${HIERMOE_PERF_MODEL_PATH}")
fi
if [[ -n "${HIERMOE_HIERARCHY_GROUP_SIZES}" && "${HIERMOE_SHOULD_PASS_PERF_MODEL}" == "1" ]]; then
    IFS=',' read -ra HIERMOE_HIERARCHY_GROUP_SIZE_ARGS <<< "${HIERMOE_HIERARCHY_GROUP_SIZES}"
    HIERMOE_ARGS+=(--train.hiermoe.hierarchy_group_sizes "${HIERMOE_HIERARCHY_GROUP_SIZE_ARGS[@]}")
fi

mkdir -p "${RUN_ROOT}" "${VERL_MOE_MONITOR_DIR}" "${VERL_MOE_TIMING_DIR}" "${VEOMNI_FULL_PROFILE_DIR}"
if [[ "${HIERMOE_FIT_PERF_MODEL_ON_STARTUP}" == "1" || "${HIERMOE_FIT_PERF_MODEL_ON_STARTUP}" == "true" ]]; then
    mkdir -p "${HIERMOE_PERF_MODEL_DIR}"
fi
if [[ "${VEOMNI_TORCH_PROFILE_ENABLE}" == "1" || "${VEOMNI_TORCH_PROFILE_ENABLE}" == "true" ]]; then
    mkdir -p "${VEOMNI_TORCH_PROFILE_DIR}"
fi
if [[ "${VEOMNI_MOE_VALIDATOR_ENABLE}" == "1" || "${VEOMNI_MOE_VALIDATOR_ENABLE}" == "true" ]]; then
    mkdir -p "${VEOMNI_MOE_VALIDATOR_DIR}"
fi

cat > "${RUN_ROOT}/launch_env_rank${NODE_RANK}.txt" <<EOF
RUN_NAME=${RUN_NAME}
RUN_ROOT=${RUN_ROOT}
MODEL_PATH=${MODEL_PATH}
DATA_PATH=${DATA_PATH}
NNODES=${NNODES}
NODE_RANK=${NODE_RANK}
NPROC_PER_NODE=${NPROC_PER_NODE}
MASTER_ADDR=${MASTER_ADDR}
MASTER_PORT=${MASTER_PORT}
MAX_STEPS=${MAX_STEPS}
MICRO_BATCH_SIZE=${MICRO_BATCH_SIZE}
GLOBAL_BATCH_SIZE=${GLOBAL_BATCH_SIZE}
MAX_SEQ_LEN=${MAX_SEQ_LEN}
DATA_NUM_WORKERS=${DATA_NUM_WORKERS}
DATA_PREFETCH_FACTOR=${DATA_PREFETCH_FACTOR}
DP_REPLICATE_SIZE=${DP_REPLICATE_SIZE}
DP_SHARD_SIZE=${DP_SHARD_SIZE}
EP_SIZE=${EP_SIZE}
NUM_MOE_LAYERS=${NUM_MOE_LAYERS}
MOE_IMPL=${MOE_IMPL}
ATTN_IMPL=${ATTN_IMPL}
MOE_MONITOR_INTERVAL=${MOE_MONITOR_INTERVAL}
VERL_MOE_PROFILE_DIR=${VERL_MOE_PROFILE_DIR}
VEOMNI_FULL_PROFILE_ENABLE=${VEOMNI_FULL_PROFILE_ENABLE}
VEOMNI_FULL_PROFILE_START_STEP=${VEOMNI_FULL_PROFILE_START_STEP}
VEOMNI_FULL_PROFILE_EVERY_N=${VEOMNI_FULL_PROFILE_EVERY_N}
VEOMNI_FULL_PROFILE_RANKS=${VEOMNI_FULL_PROFILE_RANKS}
VEOMNI_TORCH_PROFILE_ENABLE=${VEOMNI_TORCH_PROFILE_ENABLE}
VEOMNI_MOE_VALIDATOR_ENABLE=${VEOMNI_MOE_VALIDATOR_ENABLE}
VEOMNI_MOE_TIMING_SYNC_EVENTS=${VEOMNI_MOE_TIMING_SYNC_EVENTS}
HIERMOE_PLANNER_CUSTOM_OPP_PATH=${HIERMOE_PLANNER_CUSTOM_OPP_PATH}
ASCEND_CUSTOM_OPP_PATH=${ASCEND_CUSTOM_OPP_PATH:-}
HIERMOE_DEDUP_ONLY=${HIERMOE_DEDUP_ONLY}
HIERMOE_ENABLE=${HIERMOE_ENABLE}
HIERMOE_TOKEN_DEDUP=${HIERMOE_TOKEN_DEDUP}
HIERMOE_COMMUNICATION_MODE=${HIERMOE_COMMUNICATION_MODE}
HIERMOE_EXPERT_SWAP=${HIERMOE_EXPERT_SWAP}
HIERMOE_EXPERT_SWAP_INTERVAL=${HIERMOE_EXPERT_SWAP_INTERVAL}
HIERMOE_EXPERT_SWAP_MAX_PAIRS_PER_LAYER=${HIERMOE_EXPERT_SWAP_MAX_PAIRS_PER_LAYER}
HIERMOE_EXPERT_SWAP_SELECTOR=${HIERMOE_EXPERT_SWAP_SELECTOR}
HIERMOE_REDUNDANT_SLOT_INCREMENT_PER_DEVICE=${HIERMOE_REDUNDANT_SLOT_INCREMENT_PER_DEVICE}
HIERMOE_GREEDY_MAX_COPIES_PER_EXPERT=${HIERMOE_GREEDY_MAX_COPIES_PER_EXPERT}
HIERMOE_MAX_SLOT_OP_SEARCH_ROUNDS=${HIERMOE_MAX_SLOT_OP_SEARCH_ROUNDS}
HIERMOE_EXPERT_SWAP_MODE=${HIERMOE_EXPERT_SWAP_MODE}
HIERMOE_HIERARCHY_GROUP_SIZES=${HIERMOE_HIERARCHY_GROUP_SIZES}
HIERMOE_FIT_PERF_MODEL_ON_STARTUP=${HIERMOE_FIT_PERF_MODEL_ON_STARTUP}
HIERMOE_PERF_MODEL_DIR=${HIERMOE_PERF_MODEL_DIR}
HIERMOE_PERF_MODEL_PATH=${HIERMOE_PERF_MODEL_PATH}
HIERMOE_PERF_MODEL_MASTER_PORT=${HIERMOE_PERF_MODEL_MASTER_PORT}
HIERMOE_PERF_MODEL_MESSAGE_BYTES_CSV=${HIERMOE_PERF_MODEL_MESSAGE_BYTES_CSV}
HIERMOE_PERF_MODEL_WARMUP=${HIERMOE_PERF_MODEL_WARMUP}
HIERMOE_PERF_MODEL_ITERS=${HIERMOE_PERF_MODEL_ITERS}
HIERMOE_PERF_MODEL_MEASURE_LAST_N=${HIERMOE_PERF_MODEL_MEASURE_LAST_N}
HIERMOE_PERF_MODEL_HIERARCHY_GROUP_SIZES=${HIERMOE_PERF_MODEL_HIERARCHY_GROUP_SIZES}
EOF

export NPROC_PER_NODE
export VERL_MOE_PROFILE_DIR VERL_MOE_MONITOR_DIR VERL_MOE_TIMING_DIR VERL_MOE_TIMING_NUM_LAYERS
export VEOMNI_FULL_PROFILE_ENABLE VEOMNI_FULL_PROFILE_DIR VEOMNI_FULL_PROFILE_START_STEP
export VEOMNI_FULL_PROFILE_EVERY_N VEOMNI_FULL_PROFILE_RANKS VEOMNI_FULL_PROFILE_WITH_BACKWARD VEOMNI_FULL_PROFILE_RUN_KIND
export VEOMNI_TORCH_PROFILE_EXPORT_RANKS VEOMNI_TORCH_PROFILE_ACTIVITIES
export VEOMNI_MOE_VALIDATOR_ENABLE VEOMNI_MOE_VALIDATOR_DIR
export VEOMNI_MOE_TIMING_SYNC_EVENTS
export TOKENIZERS_PARALLELISM=false
export HCCL_NPU_SOCKET_PORT_RANGE=${HCCL_NPU_SOCKET_PORT_RANGE:-auto}
export HCCL_OP_EXPANSION_MODE=${HCCL_OP_EXPANSION_MODE:-AIV}
export HCCL_BUFFSIZE=${HCCL_BUFFSIZE:-16}
export HCCL_CONNECT_TIMEOUT=${HCCL_CONNECT_TIMEOUT:-7200}
export HCCL_EXEC_TIMEOUT=${HCCL_EXEC_TIMEOUT:-7200}

echo "Run root: ${RUN_ROOT}"
echo "Profile dir: ${VERL_MOE_PROFILE_DIR}"
echo "Full timing dir: ${VEOMNI_FULL_PROFILE_DIR} (enabled=${VEOMNI_FULL_PROFILE_ENABLE}, start=${VEOMNI_FULL_PROFILE_START_STEP}, every_n=${VEOMNI_FULL_PROFILE_EVERY_N}, ranks=${VEOMNI_FULL_PROFILE_RANKS})"
echo "Torch profiler dir: ${VEOMNI_TORCH_PROFILE_DIR} (enabled=${VEOMNI_TORCH_PROFILE_ENABLE})"
echo "MoE monitor interval: ${MOE_MONITOR_INTERVAL}"
echo "MoE timing sync events: ${VEOMNI_MOE_TIMING_SYNC_EVENTS}"
echo "HierMoE planner custom OPP path: ${HIERMOE_PLANNER_CUSTOM_OPP_PATH}"
echo "HierMoE dedup-only: ${HIERMOE_DEDUP_ONLY}"
echo "HierMoE enable override: ${HIERMOE_ENABLE:-<yaml default>}"
echo "HierMoE communication mode: ${HIERMOE_COMMUNICATION_MODE}"
echo "HierMoE expert swap interval: ${HIERMOE_EXPERT_SWAP_INTERVAL}"
echo "HierMoE expert swap max pairs per layer: ${HIERMOE_EXPERT_SWAP_MAX_PAIRS_PER_LAYER}"
echo "HierMoE expert swap selector: ${HIERMOE_EXPERT_SWAP_SELECTOR}"
echo "HierMoE redundant slot increment per device: ${HIERMOE_REDUNDANT_SLOT_INCREMENT_PER_DEVICE}"
echo "HierMoE greedy max copies per expert: ${HIERMOE_GREEDY_MAX_COPIES_PER_EXPERT}"
echo "HierMoE max slot-op search rounds: ${HIERMOE_MAX_SLOT_OP_SEARCH_ROUNDS:-auto}"
echo "HierMoE expert swap mode: ${HIERMOE_EXPERT_SWAP_MODE}"
echo "HierMoE hierarchy group sizes: ${HIERMOE_HIERARCHY_GROUP_SIZES:-<auto>}"
echo "HierMoE fit perf model on startup: ${HIERMOE_FIT_PERF_MODEL_ON_STARTUP}"
echo "HierMoE perf model path: ${HIERMOE_PERF_MODEL_PATH:-<none>}"
echo "torchrun: nnodes=${NNODES} node_rank=${NODE_RANK} nproc_per_node=${NPROC_PER_NODE} master=${MASTER_ADDR}:${MASTER_PORT}"

if [[ "${HIERMOE_FIT_PERF_MODEL_ON_STARTUP}" == "1" || "${HIERMOE_FIT_PERF_MODEL_ON_STARTUP}" == "true" ]]; then
    HIERMOE_PERF_BENCH_ARGS=(
        --output-json "${HIERMOE_PERF_MODEL_PATH}"
        --details-json "${HIERMOE_PERF_MODEL_DIR}/hiermoe_perf_model_details_rank${NODE_RANK}.json"
        --message-bytes-csv "${HIERMOE_PERF_MODEL_MESSAGE_BYTES_CSV}"
        --ranks-per-node "${NPROC_PER_NODE}"
        --warmup "${HIERMOE_PERF_MODEL_WARMUP}"
        --iters "${HIERMOE_PERF_MODEL_ITERS}"
        --measure-last-n "${HIERMOE_PERF_MODEL_MEASURE_LAST_N}"
    )
    if [[ -n "${HIERMOE_PERF_MODEL_HIERARCHY_GROUP_SIZES}" ]]; then
        HIERMOE_PERF_BENCH_ARGS+=(--hierarchy-group-sizes-csv "${HIERMOE_PERF_MODEL_HIERARCHY_GROUP_SIZES}")
    fi

    echo "Fitting HierMoE perf model before training step 0..."
    torchrun \
        --nnodes="${NNODES}" \
        --nproc-per-node="${NPROC_PER_NODE}" \
        --node-rank="${NODE_RANK}" \
        --master-addr="${MASTER_ADDR}" \
        --master-port="${HIERMOE_PERF_MODEL_MASTER_PORT}" \
        profile/scripts/bench_hiermoe_perf_model.py \
        "${HIERMOE_PERF_BENCH_ARGS[@]}"
fi

torchrun \
    --nnodes="${NNODES}" \
    --nproc-per-node="${NPROC_PER_NODE}" \
    --node-rank="${NODE_RANK}" \
    --master-addr="${MASTER_ADDR}" \
    --master-port="${MASTER_PORT}" \
    tasks/train_vlm.py configs/multimodal/qwen3_vl/qwen3_vl_moe.yaml \
    --model.model_path "${MODEL_PATH}" \
    --model.ops_implementation.moe_implementation "${MOE_IMPL}" \
    --model.ops_implementation.attn_implementation "${ATTN_IMPL}" \
    --model.ops_implementation.cross_entropy_loss_implementation npu \
    --model.ops_implementation.rms_norm_implementation npu \
    --model.ops_implementation.rotary_pos_emb_implementation npu \
    --model.ops_implementation.rotary_pos_emb_vision_implementation npu \
    --model.ops_implementation.swiglu_mlp_implementation eager \
    --model.ops_implementation.load_balancing_loss_implementation eager \
    --data.train_path "${DATA_PATH}" \
    --data.dataloader.type native \
    --data.datasets_type iterable \
    --data.source_name sharegpt4v_sft \
    --data.dataloader.num_workers "${DATA_NUM_WORKERS}" \
    --data.dataloader.prefetch_factor "${DATA_PREFETCH_FACTOR}" \
    --data.max_seq_len "${MAX_SEQ_LEN}" \
    --train.micro_batch_size "${MICRO_BATCH_SIZE}" \
    --train.global_batch_size "${GLOBAL_BATCH_SIZE}" \
    --train.max_steps "${MAX_STEPS}" \
    --train.num_train_epochs 1 \
    --train.accelerator.dp_replicate_size "${DP_REPLICATE_SIZE}" \
    --train.accelerator.dp_shard_size "${DP_SHARD_SIZE}" \
    --train.accelerator.ep_size "${EP_SIZE}" \
    --train.moe_load_balance_monitor_interval "${MOE_MONITOR_INTERVAL}" \
    --train.profile.enable "${VEOMNI_TORCH_PROFILE_ENABLE}" \
    --train.profile.start_step "${VEOMNI_TORCH_PROFILE_START_STEP}" \
    --train.profile.end_step "${VEOMNI_TORCH_PROFILE_END_STEP}" \
    --train.profile.trace_dir "${VEOMNI_TORCH_PROFILE_DIR}" \
    --train.profile.rank0_only "${VEOMNI_TORCH_PROFILE_RANK0_ONLY}" \
    --train.profile.record_shapes "${VEOMNI_TORCH_PROFILE_RECORD_SHAPES}" \
    --train.profile.profile_memory "${VEOMNI_TORCH_PROFILE_PROFILE_MEMORY}" \
    --train.profile.with_stack "${VEOMNI_TORCH_PROFILE_WITH_STACK}" \
    --train.profile.with_modules "${VEOMNI_TORCH_PROFILE_WITH_MODULES}" \
    --train.wandb.enable false \
    --train.checkpoint.output_dir "${RUN_ROOT}/ckpts" \
    --train.checkpoint.save_steps 0 \
    --train.checkpoint.save_epochs 0 \
    --train.checkpoint.hf_save_steps 0 \
    --train.checkpoint.hf_save_epochs 0 \
    --train.checkpoint.save_hf_weights false \
    "${HIERMOE_ARGS[@]}" \
    "$@"
