#ifndef VEOMNI_HIERMOE_REPLICA_SCORE_FUNCTION_H
#define VEOMNI_HIERMOE_REPLICA_SCORE_FUNCTION_H

#include <ATen/ATen.h>
#include <tuple>

std::tuple<at::Tensor, at::Tensor, at::Tensor> hiermoe_replica_prepare_npu(
    const at::Tensor &selected,
    int64_t num_experts);

at::Tensor hiermoe_replica_score_npu(
    const at::Tensor &route_indices,
    const at::Tensor &multiplicities,
    const at::Tensor &token_counts,
    const at::Tensor &route_ranks,
    const at::Tensor &route_scores,
    const at::Tensor &minimum_scores,
    const at::Tensor &tie_count,
    const at::Tensor &tied_rank_order,
    const at::Tensor &route_hashes,
    const at::Tensor &token_group_counts,
    const at::Tensor &candidate_experts,
    int64_t num_levels,
    int64_t level_size0,
    int64_t level_size1,
    int64_t level_size2,
    int64_t top_k);

at::Tensor hiermoe_cover_score_npu(
    const at::Tensor &selected,
    const at::Tensor &route_indices,
    const at::Tensor &multiplicities,
    const at::Tensor &token_counts,
    const at::Tensor &route_ranks,
    const at::Tensor &route_hashes,
    const at::Tensor &token_group_counts,
    const at::Tensor &copy_slots,
    const at::Tensor &candidate_rows,
    int64_t num_slots,
    int64_t slots_per_rank,
    int64_t ep_size,
    int64_t source_rank,
    int64_t num_levels,
    int64_t level_size0,
    int64_t level_size1,
    int64_t level_size2,
    int64_t top_k);

void hiermoe_replica_apply_npu(
    const at::Tensor &route_indices,
    const at::Tensor &token_counts,
    const at::Tensor &flat_logical,
    at::Tensor &route_ranks,
    const at::Tensor &route_scores,
    at::Tensor &minimum_scores,
    at::Tensor &tie_count,
    at::Tensor &tied_rank_order,
    const at::Tensor &route_hashes,
    at::Tensor &token_group_counts,
    const at::Tensor &logical_expert,
    const at::Tensor &destination_rank,
    int64_t num_levels,
    int64_t level_size0,
    int64_t level_size1,
    int64_t level_size2,
    int64_t top_k);

at::Tensor hiermoe_dual_map_npu(
    const at::Tensor &selected,
    const at::Tensor &copy_slots,
    const at::Tensor &copy_counts,
    const at::Tensor &owner_ranks,
    int64_t slots_per_rank,
    int64_t source_rank,
    int64_t ep_size,
    int64_t num_levels,
    int64_t level_size0,
    int64_t level_size1,
    int64_t step,
    int64_t layer_seed);

std::tuple<at::Tensor, at::Tensor, at::Tensor> hiermoe_quota_map_npu(
    const at::Tensor &selected,
    const at::Tensor &copy_slots,
    const at::Tensor &copy_counts,
    const at::Tensor &owner_ranks,
    const at::Tensor &quota_weights,
    const at::Tensor &quota_configured,
    const at::Tensor &token_ordinals,
    int64_t slots_per_rank,
    int64_t source_rank,
    int64_t ep_size,
    int64_t num_levels,
    int64_t level_size0,
    int64_t level_size1,
    int64_t step,
    int64_t layer_seed);

std::tuple<at::Tensor, at::Tensor, at::Tensor, at::Tensor> hiermoe_swap_search_npu(
    const at::Tensor &sample_routes,
    const at::Tensor &sample_weights,
    const at::Tensor &assignment_counts,
    const at::Tensor &slot_to_logical,
    const at::Tensor &owner_slots,
    int64_t max_swaps,
    int64_t slots_per_rank,
    int64_t ep_size,
    int64_t num_levels,
    int64_t level_size0,
    int64_t level_size1,
    int64_t level_size2,
    int64_t payload_bytes,
    double communication_scale,
    double compute_per_assignment,
    double a2a_alpha,
    double a2a_beta,
    double inter_alpha0,
    double inter_beta0,
    double inter_alpha1,
    double inter_beta1,
    double intra_alpha,
    double intra_beta,
    bool choose_min_dimension);

std::tuple<at::Tensor, at::Tensor, at::Tensor, at::Tensor> hiermoe_swap_select_npu(
    const at::Tensor &expert_token_counts,
    const at::Tensor &expert_assignment_counts,
    const at::Tensor &base_counts,
    const at::Tensor &expert_group_counts,
    const at::Tensor &sole_expert_counts,
    const at::Tensor &sole_pair_counts,
    const at::Tensor &sample_routes,
    const at::Tensor &sample_weights,
    const at::Tensor &slot_to_logical,
    const at::Tensor &owner_slots,
    const at::Tensor &expert_state_bytes,
    const at::Tensor &expert_gradient_bytes,
    int64_t max_swaps,
    int64_t slots_per_rank,
    int64_t ep_size,
    int64_t local_world_size,
    int64_t num_levels,
    int64_t level_size0,
    int64_t level_size1,
    int64_t level_size2,
    int64_t payload_bytes,
    double communication_scale,
    double compute_per_assignment,
    double a2a_alpha,
    double a2a_beta,
    double inter_alpha0,
    double inter_beta0,
    double inter_alpha1,
    double inter_beta1,
    double intra_alpha,
    double intra_beta,
    double state_intra_alpha,
    double state_intra_beta,
    double state_inter_alpha,
    double state_inter_beta,
    double gather_intra_alpha,
    double gather_intra_beta,
    double gather_inter_alpha,
    double gather_inter_beta,
    double scatter_intra_alpha,
    double scatter_intra_beta,
    double scatter_inter_alpha,
    double scatter_inter_beta,
    double runtime_cost_scale,
    bool choose_min_dimension);

std::tuple<at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor>
hiermoe_swap_select_with_stats_npu(
    const at::Tensor &expert_token_counts,
    const at::Tensor &expert_assignment_counts,
    const at::Tensor &base_counts,
    const at::Tensor &expert_group_counts,
    const at::Tensor &sole_expert_counts,
    const at::Tensor &sole_pair_counts,
    const at::Tensor &sample_routes,
    const at::Tensor &sample_weights,
    const at::Tensor &slot_to_logical,
    const at::Tensor &owner_slots,
    const at::Tensor &expert_state_bytes,
    const at::Tensor &expert_gradient_bytes,
    int64_t max_swaps,
    int64_t slots_per_rank,
    int64_t ep_size,
    int64_t local_world_size,
    int64_t num_levels,
    int64_t level_size0,
    int64_t level_size1,
    int64_t level_size2,
    int64_t payload_bytes,
    double communication_scale,
    double compute_per_assignment,
    double a2a_alpha,
    double a2a_beta,
    double inter_alpha0,
    double inter_beta0,
    double inter_alpha1,
    double inter_beta1,
    double intra_alpha,
    double intra_beta,
    double state_intra_alpha,
    double state_intra_beta,
    double state_inter_alpha,
    double state_inter_beta,
    double gather_intra_alpha,
    double gather_intra_beta,
    double gather_inter_alpha,
    double gather_inter_beta,
    double scatter_intra_alpha,
    double scatter_intra_beta,
    double scatter_inter_alpha,
    double scatter_inter_beta,
    double runtime_cost_scale,
    bool choose_min_dimension);

std::tuple<at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor>
hiermoe_replica_match_npu(
    const at::Tensor &base_counts,
    const at::Tensor &assignment_loads,
    const at::Tensor &add_group_deltas,
    const at::Tensor &add_assignment_deltas,
    const at::Tensor &remove_group_deltas,
    const at::Tensor &remove_assignment_deltas,
    const at::Tensor &slot_to_logical,
    const at::Tensor &owner_slots,
    const at::Tensor &redundant_slots,
    const at::Tensor &candidate_experts,
    const at::Tensor &expert_state_bytes,
    const at::Tensor &expert_gradient_bytes,
    int64_t max_actions,
    int64_t slots_per_rank,
    int64_t ep_size,
    int64_t local_world_size,
    int64_t num_levels,
    int64_t level_size0,
    int64_t level_size1,
    int64_t level_size2,
    int64_t payload_bytes,
    double communication_scale,
    double compute_per_assignment,
    double a2a_alpha,
    double a2a_beta,
    double inter_alpha0,
    double inter_beta0,
    double inter_alpha1,
    double inter_beta1,
    double intra_alpha,
    double intra_beta,
    double state_intra_alpha,
    double state_intra_beta,
    double state_inter_alpha,
    double state_inter_beta,
    double gather_intra_alpha,
    double gather_intra_beta,
    double gather_inter_alpha,
    double gather_inter_beta,
    double scatter_intra_alpha,
    double scatter_intra_beta,
    double scatter_inter_alpha,
    double scatter_inter_beta,
    double runtime_cost_scale,
    bool choose_min_dimension);

std::tuple<at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor>
hiermoe_replica_project_npu(
    const at::Tensor &sample_routes,
    const at::Tensor &sample_multiplicity,
    const at::Tensor &sample_weights,
    const at::Tensor &sample_sources,
    const at::Tensor &sample_ordinals,
    const at::Tensor &assignment_counts,
    const at::Tensor &seed_base_counts,
    const at::Tensor &slot_to_logical,
    const at::Tensor &owner_slots,
    const at::Tensor &redundant_slots,
    const at::Tensor &candidate_experts,
    int64_t slots_per_rank,
    int64_t ep_size,
    int64_t num_levels,
    int64_t level_size0,
    int64_t level_size1,
    int64_t level_size2,
    int64_t step,
    int64_t layer_seed);

std::tuple<at::Tensor, at::Tensor, at::Tensor, at::Tensor, at::Tensor>
hiermoe_quota_policy_npu(
    const at::Tensor &sample_routes,
    const at::Tensor &sample_multiplicity,
    const at::Tensor &sample_sources,
    const at::Tensor &sample_ordinals,
    const at::Tensor &assignment_counts,
    const at::Tensor &layouts,
    const at::Tensor &owner_slots,
    int64_t slots_per_rank,
    int64_t source_rank,
    int64_t ep_size,
    int64_t max_copies,
    int64_t samples_per_source,
    int64_t num_levels,
    int64_t level_size0,
    int64_t level_size1);

#endif
